### ISSUE TITLE
Task lists

### ISSUE THREAD

**Issue by LeeU1911** [LeeU1911/web-pomodoro#10]
The key concern that pomodoro technique addresses is *focus*. So it's very important to write down what you need to accomplish, and avoid interruptions at all cost. Therefore, it'd be nice to incorporate a todo list/task list into the tool.

**Comment by hirohaji** [comment]
I'll do it :)

**Comment by LeeU1911** [comment]
Can you fix the conflict caused by me merging a restructure PR?
