### ISSUE TITLE
Music integration

### ISSUE THREAD

**Issue by LeeU1911** [LeeU1911/web-pomodoro#11]
Integrate with music from sites like http://www.rainymood.com/ to boost productivity. 

More here: http://www.webdistortion.com/2015/04/14/focus-playlists-for-coding/

**Comment by Nfinger** [comment]
Ill take this task if its still open

**Comment by mataca9** [comment]
#19 
I did a little music player, hope could be what you were expecting for this issue.

**Comment by LeeU1911** [comment]
> #19
> I did a little music player, hope could be what you were expecting for this issue.

Thanks @mataca9. Very good starting point. Can you fix the conflict caused by me merging a restructure PR?

**Comment by LeeU1911** [comment]
> Ill take this task if its still open

Thanks @Nfinger. It was open until @mataca9 opened a PR for it. But it shouldn't prevent you from improving on what PR #19 has done.
