### ISSUE TITLE
Record interruptions when pausing/resuming pomodoro

### ISSUE THREAD

**Issue by LeeU1911** [LeeU1911/web-pomodoro#12]
It is important to know how much time you've been interrupted in order to optimize it.

**Comment by eokoneyo** [comment]
@LeeU1911 I'd like to take this one, Any specifics on how the interruptions should be displayed??

**Comment by LeeU1911** [comment]
@eokoneyo thanks. A first iteration can be recording the time if user pauses and starts Pomodoro again and displays total interupted time.  Of course, open for suggestions as well.

**Comment by eokoneyo** [comment]
Cool... I'll send in the PR soon

**Comment by medimessarat** [comment]
I can also help with more idea

**Comment by LeeU1911** [comment]
Can you fix the conflict caused by me merging a restructure PR?
