### ISSUE TITLE
How to successfully run this program locally?

### ISSUE THREAD

**Issue by jakeshin45** [LeeU1911/web-pomodoro#23]
I am trying to run the most recent version locally after doing

    npm install

and

    npm install gruntjs/grunt-contrib-uglify#harmony --save

After I type npm start, the webpage of Pomodoro opens, but Pomodoro does not start after clicking Start.

Can you guys help me to build this project? Thanks!

**Comment by LeeU1911** [comment]
Do you see any error in browser's console after running? @jakeshin45

**Comment by jakeshin45** [comment]
Yep I see these errors at console.

![Screenshot from 2019-12-07 13-20-59](https://user-images.githubusercontent.com/23709928/70378927-90e16980-18f4-11ea-8f2d-4b2d1f0749db.png)

**Comment by jakeshin45** [comment]
Nevermind. I found a way to fix this.
