### ISSUE TITLE
When starting new POMODORO The secondary CTA is not of any use

### ISSUE THREAD

**Issue by hb2708** [LeeU1911/web-pomodoro#25]
So issue here is  there are two CTA's 

1. Main CTA Which Start / Reset the POMODORO
2. Secondary CTA Which Pause / Resume the POMODORO

When we are starting new POMODORO then secondary CTA is not of any use so can hide it to me more clear.

**Comment by hb2708** [comment]
@LeeU1911 Take a look when get time.

**Comment by LeeU1911** [comment]
Hey @hb2708,

Thanks for your PR. The change works as described. 

Just wondering how one would pause a pomodoro temporarily on the occasion of dealing with distractions?
```
6. Deal with distractions: If it is non urgent (gossips, texts, distracting thoughts, etc.), note it down to get to it later in break time and come back to the thing you're working on immediately. 
```
I'd think one can pause for a bit in case someone calls or a distracting thought, you can deal with those very quickly by turning off ringtone/rejecting call if non urgent/noting down the thought, then resume the pomodoro right away.

Though I can see it makes sense to hide secondary button on first page load.

**Comment by hb2708** [comment]
@LeeU1911
As per my understanding for 

`6. Deal with distractions: If it is non urgent (gossips, texts, distracting thoughts, etc.), note it down to get to it later in break time and come back to the thing you're working on immediately. `

User can only pause POMODORO if it's active and that part is not affected.

Just now added some comments to logic and did small refactor

**Comment by LeeU1911** [comment]
@hb2708 You're right. Works as expected. I forgot to run `grunt` before testing so the style update didn't get effective. 
Approved after a small comment format change.

Thanks for contributing!
